# submit file for mapping metagenomic time series reads to the coassembly.
# run from the TroutBogReads folder
# this sets up the relative location - you can run condor_submit from folders within the submit node
#
universe = vanilla
log = $(file)_v2.log
error = $(file)_v2.err
#
executable = run_bbmap.sh
arguments = $(file)
output = $(file)_v2.out
# $cluster-> $dir
# $process->$file
#
initialdir = $(dir)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../bbmap_only,$(file)
# transfer_input_files = ../bbmap_only,/home/dgshrader/samtools-1.3,$(file)
#
request_cpus= 1
request_memory = 6 GB
request_disk = 3 GB
# +WantFlocking = true
# +WantGlideIn = true
# Requirements = Target.PoolName =!= "CHTC"
#
queue dir,file from readFileList.txt

